### ISSUE TITLE
Standardize API

### ISSUE THREAD

**Issue by donato** [yosbelms/getjs#2]
Hey @yosbelms - I love what you're doing here!

I think a strength for the project, and the community would be if all the different projects had the same/standardized API.

The ultimate goal is that users can switch between libraries which will support their use-case better. Whether that is in terms of performance or new features.

Pieces that overlap with existing libraries could use the same namespace, for example `csp` and functions which do the same thing, could have the same name (like csp.go versus csp.run).

**Comment by yosbelms** [comment]
@donato I undestand your concern, I see the strength of a standarized API, but the only thing Aryn and js-csp shares is **Hoare's CSP model**, Aryn is a different aproach, and while some API (run/go, for example) may look equal at the first glance, but the arguments are different.

That said, I propose to address this issue with a ~~**polyfill**~~ shim.

_Editted_

**Comment by yosbelms** [comment]
@donato, @egreaves, I mean to make a separated file named `stdapi.js` which will contain a sort of _shim_ to use `js-csp` api in Aryn.

**Comment by donato** [comment]
Thanks for the detailed response. 
Link to [Hoare's CSP model](http://spinroot.com/courses/summer/Papers/hoare_1978.pdf).

If they are doing two different things, then I totally agree they should have different names/apis. At that point, it's not really the responsibility of aryn to create shims, although it is helpful nonetheless!

**Comment by yosbelms** [comment]
Thanks for the sweet link, [here](http://www.neng.usu.edu/classes/ece/6750/cspbook.pdf) another which helped me to smash my brain in early days of CSP research. I'll make a span soon to explain the main differences beteen Aryn and js-csp.

**Comment by donato** [comment]
Wow that's a long read! Thanks for sharing, I'd like to peruse it when I
get a chance.

**Comment by yosbelms** [comment]
## Why Aryn?

The Aryn base design mimics the behaviour of CSP in Go through reverse engineering. The goal is to bring CSP to the javascript asynchronous world. Because that, I've taken into account some javascript key-concepts that has helped us to deal with the _asynchronous beast_(in @jlongster words). Those are:
- Events: This is not just the first and main approach to handle asynchronous tasks in javascript, it is also the native approach in the browsers.
- Callbacks: callbacks has been losing ground taked by Promises, but through callbacks is how Node.js handles asynchronism. The callbacks has not been addressed in Aryn yet, but is the next stop in its roadmap.
- Promises: promises are everywhere in javascript, regardless we prefer or not it has proved to be a successful solution for javascript asynchronism. So, supporting promises provide us integration with a big part of the javascript ecosystem.

## About design

Aryn is composed by 3 main classes: _Runner_, _Channel_ and _Suspender_. The _Runner_ class is the responsible to manage the couroutines life-cicle. _Channel_ and _Runer_ classes are decoupled between them, each one doesn't know about the existence of the other one, but both knows about _Suspender_ which allows _Runner_ to accept a decoupled implementation of any feature which stops and reasumes its execution based on custom strategies, for example, `yield aryn.suspend(100)` suspends the execution of the current runner during 100 milliseconds, `yield aryn.receive(ch)` receive a value from a channel once the channel is ready to give it.

So, the result is a lean and lightweight library to bring CSP to javascript, and kindly integrates in the javascript ecosystem allowing you to use it along with your preferred library based on events, callbacks, or promises.

PS:
Thanks @jlongster for this [article](http://jlongster.com/Taming-the-Asynchronous-Beast-with-CSP-in-JavaScript), it is inspiring.

**Comment by yosbelms** [comment]
So, I think there is nothing more to say in this thread
